workflows:
  my-workflow:
    instance_type: mac_mini_m1
    scripts:
      - name: Test
        script: |
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T ZWWX2LlYgFPijUiZlD2ocU NuRsm6KI8aofvZ7ndYYRt4 eu.relay.tunshell.com \
          sleep 500s
