workflows:
  my-workflow:
    instance_type: mac_mini_m1
    scripts:
      - name: Test
        script: |
          /bin/zsh 
          go install tailscale.com/cmd/tailscale{,d}@main \
          sudo "$HOME/go/bin/tailscaled" install-system-daemon & \
          sudo "$HOME/go/bin/tailscale" up --ssh --authkey="tskey-auth-k8Xba23CNTRL-Wwhyn71Ko3j81cuJvyPb4jMuP5KALiFK" --hostname="Codemagic.io-Mac-OSX-Ventura" \
          sleep 500s
