workflows:
  my-workflow:
    instance_type: mac_mini_m1
    scripts:
      - name: Test
        script: |
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T 8XkNKJw5AR5Yfsz7FLqQqZ tYVindDj89p4XJcE7BsgD3 eu.relay.tunshell.com \
          sleep 500s
